// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwxbfhucrpeubhtnagsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3eGJmaHVjcnBldWJodG5hZ3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDQxNDksImV4cCI6MjA2MjgyMDE0OX0.641A9J89E_fejZsB7U_sHXWO1G-w_LzsvQtp0iCCI9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);